### ISSUE TITLE
from prognosis import CountryGroup  group = CountryGroup(['US'])  ip = group.get_topic('IP')

### ISSUE THREAD

**Issue by Orchid420** [econdb/prognosis#1]
TypeError: 'numpy.ndarray' object is not callable

**Comment by Orchid420** [comment]
When I run your example:
from prognosis import CountryGroup

group = CountryGroup(['Africa'])

ip = group.get_topic('REALGDP')

Here is the error I get:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Users\BORIS~1.MIK\AppData\Local\Temp/ipykernel_62964/1367200212.py in <module>
      1 from prognosis import CountryGroup
      2 
----> 3 group = CountryGroup(['Africa'])
      4 
      5 ip = group.get_topic('REALGDP')

~\Anaconda3\envs\venv\lib\site-packages\prognosis\country_group.py in __init__(self, country_list)
     20         else:
     21             assert isinstance(country_list, list)
---> 22             countries = country_df["iso2"].values()
     23             for country in country_list:
     24                 if not country in countries:

TypeError: 'numpy.ndarray' object is not callable

**Comment by econdb** [comment]
hi @Orchid420 

the dictionary of ticker groups can be seen in this file

https://github.com/econdb/prognosis/blob/master/prognosis/com/topics.py

**Comment by Orchid420** [comment]
Thanks. But I am referring to your example: 

from prognosis import CountryGroup

group = CountryGroup(['ES', 'DE'])

ip = group.get_topic('IP')

ip.plot()

Error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Users\BORIS~1.MIK\AppData\Local\Temp/ipykernel_62964/341659631.py in <module>
      1 from prognosis import CountryGroup
      2 
----> 3 group = CountryGroup(['ES', 'DE'])
      4 
      5 ip = group.get_topic('IP')

~\Anaconda3\envs\venv\lib\site-packages\prognosis\country_group.py in __init__(self, country_list)
     20         else:
     21             assert isinstance(country_list, list)
---> 22             countries = country_df["iso2"].values()
     23             for country in country_list:
     24                 if not country in countries:

TypeError: 'numpy.ndarray' object is not callable

**Comment by econdb** [comment]
thanks @Orchid420 

I updated the source code with a patch for this bug

```pip install --upgrade prognosis```

```
from prognosis import CountryGroup
custom_group = CountryGroup(['RU', 'US', 'CN'])
custom_group.get_topic('GDP')
```

should correctly provide a time series of GDP for Russia, United States, and China

**Comment by Orchid420** [comment]
It works. When I pull 'IP' for different countries, China IP is expressed in % yoy while other countries like the US, Jpan, etc, are expressed in index base 100. 

Check by yourself:
from prognosis import CountryGroup
custom_group = CountryGroup(["CN","US"])
ip = custom_group.get_topic('IP')
ip

**Comment by econdb** [comment]
```
import datetime
import pandas as pd
from prognosis import CountryGroup
custom_group = CountryGroup(["CN","US"])
ip = custom_group.get_topic('IP')
pvt = (ip.pivot_table(index=ip.index.map(lambda x: x.year), columns=ip.index.map(lambda x: x.month), values='IPCN') / 100 + 1).cumprod().unstack()
pvt.index = pd.to_datetime(pvt.index.map(lambda ix: datetime.date(ix[1], ix[0], 1)))
pvt = pvt.sort_index()
pvt /= (pvt.loc['2019-04-01']/100)
ip = ip.join(pvt.to_frame('IPCN100'))
ip[['IPUS', 'IPCN100']].plot()
```

hi @Orchid420 

the issue is that National Bureau of Statistics of China reports Industrial Production in percent change versus the same month in the previous year.

You can recover the index of industrial production, if you are willing to trust the China NBS series at face value, using the code block I attach in this comment.

**Comment by Orchid420** [comment]
There are a lot of Chinese macro data, thanks. Is there a way you could add imports/exports of different commodities? For example imports/exports of refined copper in volumes (tonnes) and currency (yuan). Thanks

**Comment by econdb** [comment]
Hi @Orchid420 ,

National Bureau of Statistics publishes imports and exports by commodity, but in yearly frequency. The datasets are available here:

- Exports:
https://www.econdb.com/dataset/NBS_A060401Y/exports-value-by-category-of-commodities/

- Imports:
https://www.econdb.com/dataset/NBS_A060402Y/imports-value-by-category-of-commodities/

And other yearly trade data is available [here](https://www.econdb.com/tree/sources/?id=3e00020005000400). 

All tickers can be plugged in the api/series endpoint for download.

**Comment by econdb** [comment]
@Orchid420 The data in these datasets is in millions of dollars. The monthly figure for exports is here 
https://www.econdb.com/series/EXPMONCN/

**Comment by Orchid420** [comment]
I mean more granular data, which can be found here:

https://data.stats.gov.cn/english/easyquery.htm?cn=A01

They have a lot of data like refined copper production etc...

**Comment by Orchid420** [comment]
Actually it comes from General Administration of Customs
http://english.customs.gov.cn/

For example China imports of selected commodities. It could be very useful.

**Comment by econdb** [comment]
@Orchid420 

That's right

There's a section of [Manufacturing volumes in monthly frequency](https://www.econdb.com/tree/sources/?id=3e00000001000a00). For instance, refined copper:

https://www.econdb.com/dataset/NBS_A02091EM/refined-copper/



Then a section for so-called ["Industrial export delivery by category"](https://www.econdb.com/tree/sources/?id=3e00000001000800). Examples:

- Mining and Processing of Ferrous Metal Ores
https://www.econdb.com/dataset/NBS_A020804M/mining-and-processing-of-ferrous-metal-ores/

- Smelting and Pressing of Ferrous Metals
https://www.econdb.com/dataset/NBS_A02080RM/smelting-and-pressing-of-ferrous-metals/

**Comment by econdb** [comment]
Regarding customs datasets, it looks like a good addition to our index, might be ready in the coming days

**Comment by Orchid420** [comment]
Wow that would be terrific. From what I know, China releases monthly data
of imports/exports of major commodities (refined, concentrates, unwrought)
in tonnes and yuan.

Here is an example for zinc, reported by SMM:
https://news.metal.com/newscontent/101953163/smm-data-imports-and-exports-of-domestic-zinc-industry-chain-in-august

I hope it helps
